openapi: 3.0.3
info:
  title: Search Index REST API
  version: 1.0.0
  description: Public REST API for querying Search Index plugin indexes.
servers:
  - url: https://cogappcraft-search-ui-production.up.railway.app/search-index/api
    description: Production (Railway)
  - url: /search-index/api
    description: Current site relative
paths:
  /meta:
    get:
      summary: Get index metadata
      parameters:
        - in: query
          name: index
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Metadata response
          content:
            application/json:
              schema:
                type: object
                properties:
                  roles:
                    type: object
                    additionalProperties:
                      type: string
                  facetFields:
                    type: array
                    items:
                      type: string
                  sortOptions:
                    type: array
                    items:
                      type: object
                      properties:
                        label:
                          type: string
                        value:
                          type: string
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
  /search:
    get:
      summary: Run a search
      parameters:
        - $ref: '#/components/parameters/IndexParam'
        - in: query
          name: query
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
        - in: query
          name: perPage
          schema:
            type: integer
            minimum: 1
            default: 20
        - in: query
          name: facets
          description: Comma-separated facet field names.
          schema:
            type: string
            example: placeRegion,placeCountry
        - in: query
          name: maxValuesPerFacet
          schema:
            type: integer
            minimum: 1
        - in: query
          name: fields
          description: Comma-separated fields to search within.
          schema:
            type: string
            example: title,summary
        - in: query
          name: sort
          description: URL-encoded JSON object, e.g. {"field":"asc"}.
          schema:
            type: string
        - in: query
          name: filters
          description: URL-encoded JSON object.
          schema:
            type: string
        - in: query
          name: highlight
          schema:
            type: boolean
        - in: query
          name: suggest
          schema:
            type: boolean
        - in: query
          name: stats
          description: Comma-separated numeric field names.
          schema:
            type: string
        - in: query
          name: histogram
          description: URL-encoded JSON object of histogram intervals.
          schema:
            type: string
        - in: query
          name: geoFilter
          description: 'URL-encoded JSON object: `{"lat": 51.5, "lng": -0.1, "radius": "50km"}`'
          schema:
            type: string
        - in: query
          name: geoSort
          description: 'URL-encoded JSON object: `{"lat": 51.5, "lng": -0.1}`'
          schema:
            type: string
        - in: query
          name: geoGrid
          description: 'URL-encoded JSON object: `{"field": "placeCoordinates", "precision": 6, "bounds": {"top_left": {"lat": 55, "lon": -5}, "bottom_right": {"lat": 50, "lon": 2}}}`. ES/OpenSearch only. Precision maps to slippy map zoom levels (0-29). When bounds are provided, only tiles within the viewport are returned.'
          schema:
            type: string
        - in: query
          name: vectorSearch
          schema:
            type: boolean
        - in: query
          name: voyageModel
          schema:
            type: string
        - in: query
          name: embeddingField
          schema:
            type: string
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResult'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /autocomplete:
    get:
      summary: Run lightweight autocomplete
      parameters:
        - $ref: '#/components/parameters/IndexParam'
        - in: query
          name: query
          required: true
          schema:
            type: string
        - in: query
          name: perPage
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 5
      responses:
        '200':
          description: Autocomplete results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResult'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /facet-values:
    get:
      summary: Search values for a facet field
      parameters:
        - $ref: '#/components/parameters/IndexParam'
        - in: query
          name: facetField
          required: true
          schema:
            type: string
        - in: query
          name: query
          schema:
            type: string
        - in: query
          name: maxValues
          schema:
            type: integer
            minimum: 1
            default: 10
        - in: query
          name: filters
          description: URL-encoded JSON object.
          schema:
            type: string
      responses:
        '200':
          description: Facet values
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FacetValue'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /document:
    get:
      summary: Get a single document by ID
      parameters:
        - $ref: '#/components/parameters/IndexParam'
        - in: query
          name: documentId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Document payload
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /multi-search:
    get:
      summary: Run multiple searches in one request
      description: |
        Batches multiple search queries in a single HTTP request.
        Each search definition in the `searches` array supports the same parameters as `/search`
        (query, page, perPage, facets, maxValuesPerFacet, filters, sort, fields, highlight, suggest,
        stats, histogram, geoFilter, geoSort, geoGrid). Each search can target a different index.
        The response is an array of SearchResult objects in the same order as the input.
      parameters:
        - in: query
          name: searches
          required: true
          description: |
            URL-encoded JSON array of search definitions. Each object supports:
            `index` (required), `query`, `page`, `perPage`, `facets`, `maxValuesPerFacet`,
            `filters`, `sort`, `fields`, `highlight`, `suggest`, `stats`, `histogram`,
            `geoFilter`, `geoSort`, `geoGrid`.
          schema:
            type: string
      responses:
        '200':
          description: Array of search results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SearchResult'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /related:
    get:
      summary: Find related documents (More Like This)
      description: Returns documents similar to the given source document using the engine's native MLT/related-search capability.
      parameters:
        - $ref: '#/components/parameters/IndexParam'
        - in: query
          name: documentId
          required: true
          description: The ID of the source document to find related content for.
          schema:
            type: string
        - in: query
          name: perPage
          description: Maximum number of related documents to return.
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 5
        - in: query
          name: fields
          description: Comma-separated field names to base similarity on. Uses engine defaults when omitted.
          schema:
            type: string
            example: title,summary
      responses:
        '200':
          description: Related documents
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelatedResult'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /stats:
    get:
      summary: Get index statistics
      description: Returns the document count, engine name, and existence status for an index.
      parameters:
        - $ref: '#/components/parameters/IndexParam'
      responses:
        '200':
          description: Index statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndexStatsResult'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
components:
  parameters:
    IndexParam:
      in: query
      name: index
      required: true
      schema:
        type: string
  responses:
    ErrorResponse:
      description: Error response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Error:
      type: object
      required: [error]
      properties:
        error:
          type: string
    FacetValue:
      type: object
      properties:
        value:
          type: string
        count:
          type: integer
      required: [value, count]
    SearchResult:
      type: object
      properties:
        totalHits:
          type: integer
        page:
          type: integer
        perPage:
          type: integer
        totalPages:
          type: integer
        processingTimeMs:
          type: integer
        hits:
          type: array
          items:
            type: object
            additionalProperties: true
        facets:
          type: object
          nullable: true
          additionalProperties: true
        stats:
          type: object
          nullable: true
          additionalProperties: true
        histograms:
          type: object
          nullable: true
          additionalProperties: true
        suggestions:
          type: array
          nullable: true
          items:
            type: string
        geoClusters:
          type: array
          nullable: true
          description: Geo grid aggregation clusters (ES/OpenSearch only, requires geoGrid param). Coordinates are actual document centroids (via geo_centroid sub-aggregation), not tile centres.
          items:
            type: object
            properties:
              lat:
                type: number
                description: Centroid latitude of documents in this tile.
              lng:
                type: number
                description: Centroid longitude of documents in this tile.
              count:
                type: integer
                description: Number of documents in this tile.
              key:
                type: string
                description: Geotile key in "zoom/x/y" format.
              hit:
                type: object
                nullable: true
                description: Sample hit from this tile (for popup/preview data). Includes resolved _roles and _responsiveImages.
                additionalProperties: true
    RelatedResult:
      type: object
      properties:
        totalHits:
          type: integer
        hits:
          type: array
          items:
            type: object
            additionalProperties: true
        processingTimeMs:
          type: integer
          nullable: true
    IndexStatsResult:
      type: object
      properties:
        index:
          type: string
        engine:
          type: string
          description: Display name of the search engine (e.g. "Elasticsearch", "Algolia").
        documentCount:
          type: integer
        indexExists:
          type: boolean
